"""Thin vs thick equivalence check (run as a script).

In the thin limit (very small effective thickness T) a polarized "(thick)" model
at orientation (theta_h, phi_h) must reproduce the corresponding THIN model whose
asymmetry is recomputed analytically from the angle:

    cos(beta) = sin(theta_h) * cos(phi_h)
    A = 2 cos^2(beta) / (1 + cos^2(beta))      (Doublet, Sextet, MDGD, Relax_MS, Relax_2S)

(All other parameters are identical, I1/I3 unchanged.) For Hamilton_mc the thin
equal is Hamilton_mc itself with the same (theta, phi). ASM has no single-A thin
equal (orientation varies along the cycloid) and is excluded.

Writes ``docs/thick_vs_thin.md``. Run:
    python tests/compare_thick_thin.py
"""
import os
import numpy as np
import syncmoss.models as m

E = np.linspace(-12.0, 12.0, 600)
T_SMALL = 1e-3
ORIENTS = [(30.0, 40.0), (60.0, 25.0), (80.0, 70.0)]


def ti(model, p, mett=0):
    return np.asarray(
        m.TImod(E, np.array(p, float), np.array([model]), E, 0.0, 1.0,
                np.array([]), [], [], Met=-1, Mett=mett),
        dtype=float,
    )


def asym_from_angles(theta_h_deg, phi_h_deg):
    cb = np.sin(np.deg2rad(theta_h_deg)) * np.cos(np.deg2rad(phi_h_deg))
    c2 = cb * cb
    return 2.0 * c2 / (1.0 + c2), cb


# builders: given (T, theta_h, phi_h) return (thin_model, thin_p, thick_model, thick_p, A)
def doublet(T, th, ph):
    A, _ = asym_from_angles(th, ph)
    d, e, L, G1, ratio = 0.2, 0.8, 0.098, 0.2, 1.0
    thin = [T, d, e, L, G1, A, ratio]
    thick = [T, d, e, L, G1, th, ph, 1.0, ratio]  # texture A=1 -> single crystal
    return 'Doublet', thin, 'Doublet_(thick)', thick, A


def sextet(T, th, ph):
    A, _ = asym_from_angles(th, ph)
    d, e, H, L, G, ap, am, GH, I13 = 0.1, -0.05, 33.0, 0.098, 0.12, 0.02, -0.01, 0.3, 3.0
    thin = [T, d, e, H, L, G, A, ap, am, GH, I13]
    thick = [T, d, e, H, L, G, th, ph, 1.0, ap, am, GH, I13]  # texture A=1 -> single crystal
    return 'Sextet', thin, 'Sextet_(thick)', thick, A


def mdgd(T, th, ph):
    A, _ = asym_from_angles(th, ph)
    d, e, H, L, G, GH, Dde, DdH, DeH, ap, am, I13 = 0.1, -0.05, 33.0, 0.098, 0.12, 0.3, 0.1, 0.1, 0.1, 0.02, -0.01, 3.0
    thin = [T, d, e, H, L, G, GH, Dde, DdH, DeH, A, ap, am, I13]
    thick = [T, d, e, H, L, G, GH, Dde, DdH, DeH, th, ph, 1.0, ap, am, I13]  # texture A=1 -> single crystal
    return 'MDGD', thin, 'MDGD_(thick)', thick, A


def relax_ms(T, th, ph):
    A, _ = asym_from_angles(th, ph)
    d, e, H, L, R, alfa, S = 0.1, -0.05, 33.0, 0.098, 0.3, 1.0, 5.0
    thin = [T, d, e, H, L, A, R, alfa, S]
    thick = [T, d, e, H, L, th, ph, 1.0, R, alfa, S]  # texture A=1 -> single crystal
    return 'Relax_MS', thin, 'Relax_MS_(thick)', thick, A


def relax_2s(T, th, ph):
    A, _ = asym_from_angles(th, ph)
    d1, e1, H1, d2, e2, H2, L, W, R = 0.1, -0.05, 33.0, 0.0, 0.0, -30.0, 0.12, 0.3, 1.0
    thin = [T, d1, e1, H1, d2, e2, H2, L, A, W, R]
    thick = [T, d1, e1, H1, d2, e2, H2, L, th, ph, 1.0, W, R]  # texture A=1 -> single crystal
    return 'Relax_2S', thin, 'Relax_2S_(thick)', thick, A


def hamilton(T, th, ph):
    d, Q, H, L, G, eta, tH, pH = 0.1, 0.4, 33.0, 0.098, 0.12, 0.3, 20.0, 30.0
    thin = [T, d, Q, H, L, G, eta, tH, pH, th, ph]
    thick = [T, d, Q, H, L, G, eta, tH, pH, th, ph, 35.0]  # alpha_k arbitrary
    return 'Hamilton_mc', thin, 'Hamilton_mc_(thick)', thick, None


BUILDERS = [doublet, sextet, mdgd, relax_ms, relax_2s, hamilton]

rows = []
worst = 0.0
for build in BUILDERS:
    for (th, ph) in ORIENTS:
        thin_name, thin_p, thick_name, thick_p, A = build(T_SMALL, th, ph)
        st = ti(thin_name, thin_p)
        sk = ti(thick_name, thick_p)
        depth = float(np.max(np.abs(1.0 - st)))            # signal depth of the thin spectrum
        maxabs = float(np.max(np.abs(st - sk)))
        rel = maxabs / depth if depth > 0 else 0.0
        worst = max(worst, rel)
        # contrast: at T=1 the two models genuinely differ (thick != thin)
        _, thin1, _, thick1, _ = build(1.0, th, ph)
        big = float(np.max(np.abs(ti(thin_name, thin1) - ti(thick_name, thick1))))
        rows.append((thick_name, th, ph, '' if A is None else f"{A:.4f}", maxabs, rel, big))

lines = []
lines.append("# Thin vs thick equivalence (small-T limit)\n")
lines.append("Generated by `tests/compare_thick_thin.py`.\n")
lines.append(f"Each thick model at orientation $(\\theta_h,\\varphi_h)$ is compared to its thin "
             f"twin with asymmetry $A=2\\cos^2\\beta/(1+\\cos^2\\beta)$, "
             f"$\\cos\\beta=\\sin\\theta_h\\cos\\varphi_h$ (Hamilton: same $(\\theta,\\varphi)$, no $A$). "
             f"All other parameters identical. Effective thickness $T={T_SMALL:g}$; "
             f"spectrum on {len(E)} points over $[-12,12]$ mm/s.\n")
lines.append("| thick model | θh | φh | A (thin) | max abs diff (T=%g) | rel. to signal | max abs diff (T=1) |" % T_SMALL)
lines.append("|---|---:|---:|---:|---:|---:|---:|")
for (name, th, ph, A, maxabs, rel, big) in rows:
    lines.append(f"| {name} | {th:g} | {ph:g} | {A} | {maxabs:.2e} | {rel:.2e} | {big:.2e} |")
lines.append("")
lines.append(f"**Worst relative thin-vs-thick difference at $T={T_SMALL:g}$: {worst:.2e}** "
             f"(→ 0 as $T\\to0$). The last column shows the two models genuinely differ at "
             f"normal thickness ($T=1$), i.e. the equivalence is a small-$T$ property only.")
lines.append("")

dst = os.path.join(os.path.dirname(__file__), '..', 'docs', 'thick_vs_thin.md')
dst = os.path.abspath(dst)
with open(dst, 'w', encoding='utf-8') as f:
    f.write("\n".join(lines))
print("worst relative diff (small T):", worst)
for r in rows:
    print(r)
print("wrote", dst)
